In [2]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
training=pd.read_csv('machine learning/datasets/0000000000002429_training_titanic_x_y_train.csv').copy()
testing=pd.read_csv('machine learning/datasets/0000000000002429_test_titanic_x_test.csv').copy()

In [3]:
training

Pclass                                               Name     Sex    Age  \
0         2      Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.00   
1         3                  Williams, Mr. Howard Hugh "Harry"    male    NaN   
2         2     Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.00   
3         3        Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.00   
4         3                             Sutehall, Mr. Henry Jr    male  25.00   
5         3                         Lemberopolous, Mr. Peter L    male  34.50   
6         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.00   
7         3                                 Jonkoff, Mr. Lalio    male  23.00   
8         2                       Williams, Mr. Charles Eugene    male    NaN   
9         3                           Rouse, Mr. Richard Henry    male  50.00   
10        3                    Stanley, Miss. Amy Zillah Elsie  female  23.00   
11        3                                  Kassem, Mr. Fared    male    NaN   
12        2                            Fox, Mr. Stanley Hubert    male  36.00   
13        3                                  Lennon, Mr. Denis    male    NaN   
14        3                         Healy, Miss. Hanora "Nora"  female    NaN   
15        3                       Gustafsson, Mr. Johan Birger    male  28.00   
16        3                                  Jonsson, Mr. Carl    male  32.00   
17        3                                Abbing, Mr. Anthony    male  42.00   
18        1                          Graham, Mr. George Edward    male  38.00   
19        3                                Jermyn, Miss. Annie  female    NaN   
20        1                    Reuchlin, Jonkheer. John George    male  38.00   
21        3                      Boulos, Mrs. Joseph (Sultana)  female    NaN   
22        2  Watt, Mrs. James (Elizabeth "Bessie" Inglis Mi...  female  40.00   
23        3                      Sawyer, Mr. Frederick Charles    male  24.50   
24        3                            Masselmani, Mrs. Fatima  female    NaN   
25        3                       Sage, Miss. Constance Gladys  female    NaN   
26        1                             Andrews, Mr. Thomas Jr    male  39.00   
27        1                                Ringhini, Mr. Sante    male  22.00   
28        3                             Eklund, Mr. Hans Linus    male  16.00   
29        2                         Matthews, Mr. William John    male  30.00   
..      ...                                                ...     ...    ...   
638       3                               Davies, Mr. Alfred J    male  24.00   
639       2  Laroche, Mrs. Joseph (Juliette Marie Louise La...  female  22.00   
640       3                                 Lefebre, Miss. Ida  female    NaN   
641       3                                Jussila, Mr. Eiriik    male  32.00   
642       1                  Calderhead, Mr. Edward Pennington    male  42.00   
643       3                         Kallio, Mr. Nikolai Erland    male  17.00   
644       1                                Baumann, Mr. John D    male    NaN   
645       2                    Richards, Master. George Sibley    male   0.83   
646       3                   Ford, Miss. Robina Maggie "Ruby"  female   9.00   
647       1                            Kent, Mr. Edward Austin    male  58.00   
648       2                                  Harper, Rev. John    male  28.00   
649       3                                    Adams, Mr. John    male  26.00   
650       3                        Vander Cruyssen, Mr. Victor    male  47.00   
651       3                         Thorneycroft, Mr. Percival    male    NaN   
652       2            West, Mrs. Edwy Arthur (Ada Mary Worth)  female  33.00   
653       3     Robins, Mrs. Alexander A (Grace Charity Laury)  female  47.00   
654       3                                Todoroff, Mr. Lalio    male    NaN   
655       1                       Ki

In [4]:
training['Ticket'].value_counts()

347082           6
1601             6
3101295          6
S.O.C. 14879     5
CA. 2343         5
W./C. 6608       4
347077           4
4133             4
347088           4
17421            4
PC 17757         4
CA 2144          3
24160            3
19950            3
382652           3
F.C.C. 13529     3
35273            3
345773           3
248727           3
110413           3
PC 17572         3
113760           3
PC 17582         3
C.A. 34651       3
LINE             3
29106            3
349909           3
113781           3
239853           3
WE/P 5735        2
                ..
A/4 45380        1
113804           1
4137             1
7540             1
14973            1
C.A. 2673        1
A/4. 34244       1
347064           1
2665             1
S.O./P.P. 751    1
29103            1
370373           1
2629             1
239856           1
231945           1
237442           1
36568            1
PC 17596         1
250652           1
113572           1
2695             1
2685        

In [5]:
title_training=[]
for i in training['Name']:
    title_training.append(i.split(',')[1].split('.')[0].strip())
title_training=np.array(title_training)
title_training[title_training=='Master']=0
title_training[title_training=='Miss']=1
title_training[title_training=='Mr']=2
title_training[title_training=='Mrs']=3
title_training[(title_training!='0')&(title_training!='1')&(title_training!='2')&(title_training!='3')]=4
title_training=np.array(title_training, dtype='int')
title_training
#'Master', 'Miss', 'Mr', 'Mrs'

array([3, 2, 2, 3, 2, 2, 3, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 4, 3,
       3, 2, 3, 1, 2, 2, 2, 2, 3, 2, 2, 1, 4, 2, 0, 0, 2, 2, 2, 2, 3, 1,
       2, 2, 2, 2, 3, 2, 1, 0, 2, 3, 2, 1, 2, 2, 2, 3, 2, 2, 2, 3, 1, 3,
       2, 2, 2, 2, 3, 2, 2, 2, 2, 1, 1, 4, 3, 3, 3, 2, 3, 2, 1, 2, 2, 2,
       2, 2, 3, 3, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2,
       1, 3, 2, 1, 2, 2, 2, 2, 1, 1, 3, 4, 1, 1, 1, 2, 2, 2, 2, 3, 2, 1,
       2, 2, 2, 3, 2, 2, 2, 4, 2, 3, 2, 2, 2, 2, 3, 2, 1, 1, 3, 2, 3, 1,
       3, 2, 3, 2, 1, 3, 3, 1, 2, 2, 2, 4, 2, 2, 2, 0, 2, 4, 3, 2, 4, 1,
       3, 2, 2, 2, 2, 1, 3, 2, 3, 0, 2, 1, 3, 2, 2, 1, 1, 2, 2, 2, 2, 2,
       2, 2, 1, 4, 1, 2, 1, 2, 3, 2, 2, 0, 3, 3, 1, 2, 1, 2, 2, 0, 1, 1,
       1, 2, 3, 2, 2, 2, 3, 2, 3, 2, 2, 0, 3, 2, 2, 2, 2, 3, 2, 1, 2, 2,
       2, 3, 2, 2, 1, 3, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 3, 2, 2, 4,
       2, 2, 3, 2, 2, 2, 0, 0, 2, 3, 1, 2, 2, 0, 2, 2, 2, 3, 1, 2, 2, 1,
       1, 2, 2, 2, 1, 2, 2, 1, 3, 1, 0, 2, 2, 1, 2,

In [6]:
testing

Pclass                                               Name     Sex    Age  \
0         2                     Davies, Master. John Morgan Jr    male   8.00   
1         1                        Leader, Dr. Alice (Farnham)  female  49.00   
2         3                            Kilgannon, Mr. Thomas J    male    NaN   
3         2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.00   
4         1                          McGough, Mr. James Robert    male  36.00   
5         1                            Artagaveytia, Mr. Ramon    male  71.00   
6         3                          de Pelsmaeker, Mr. Alfons    male  16.00   
7         3                                 Scanlan, Mr. James    male    NaN   
8         3                    Pettersson, Miss. Ellen Natalia  female  18.00   
9         3                                Smiljanic, Mr. Mile    male    NaN   
10        1                  Andrews, Miss. Kornelia Theodosia  female  63.00   
11        3                                 Sdycoff, Mr. Todor    male    NaN   
12        1                     Hays, Miss. Margaret Bechstein  female  24.00   
13        3                       Heininen, Miss. Wendla Maria  female  23.00   
14        1                          Goldschmidt, Mr. George B    male  71.00   
15        2                        Giles, Mr. Frederick Edward    male  21.00   
16        3                     Kalvik, Mr. Johannes Halvorsen    male  21.00   
17        3                    Johnson, Master. Harold Theodor    male   4.00   
18        3                          Karlsson, Mr. Nils August    male  22.00   
19        3                       Hegarty, Miss. Hanora "Nora"  female  18.00   
20        3                                Moran, Miss. Bertha  female    NaN   
21        3                                Dooley, Mr. Patrick    male  32.00   
22        1                           Bonnell, Miss. Elizabeth  female  58.00   
23        2                                Herman, Miss. Alice  female  24.00   
24        3                                  Keefe, Mr. Arthur    male    NaN   
25        1             Williams-Lambert, Mr. Fletcher Fellows    male    NaN   
26        2                      Banfield, Mr. Frederick James    male  28.00   
27        1                     Holverson, Mr. Alexander Oskar    male  42.00   
28        3                             Baclini, Miss. Eugenie  female   0.75   
29        2                               Ridsdale, Miss. Lucy  female  50.00   
..      ...                                                ...     ...    ...   
193       3                           Moutal, Mr. Rahamin Haim    male    NaN   
194       3                                    Rekic, Mr. Tido    male  38.00   
195       3                             Heikkinen, Miss. Laina  female  26.00   
196       1                       Hippach, Miss. Jean Gertrude  female  16.00   
197       3                     Laitinen, Miss. Kristina Sofia  female  37.00   
198       2        Clarke, Mrs. Charles V (Ada Maria Winfield)  female  28.00   
199       1  Rothes, the Countess. of (Lucy Noel Martha Dye...  female  33.00   
200       3                                   Tobin, Mr. Roger    male    NaN   
201       1                          Stahelin-Maeglin, Dr. Max    male  32.00   
202       3                             Perkin, Mr. John Henry    male  22.00   
203       1                                  Gee, Mr. Arthur H    male  47.00   
204       3                                McMahon, Mr. Martin    male    NaN   
205       3               Hagland, Mr. Konrad Mathias Reiersen    male    NaN   
206       3                                    Chip, Mr. Chang    male  32.00   
207       3                          Bostandyeff, Mr. Guentcho    male  26.00   
208       1          Stone, Mrs. George Nelson (Martha Evelyn)  female  62.00   
209       3                                 Skoog, Miss. Mabel  female   9.00   
210       3                         

In [7]:
title_testing=[]
for i in testing['Name']:
    title_testing.append(i.split(',')[1].split('.')[0].strip())
title_testing=np.array(title_testing)
title_testing[title_testing=='Master']=0
title_testing[title_testing=='Miss']=1
title_testing[title_testing=='Mr']=2
title_testing[title_testing=='Mrs']=3
title_testing[(title_testing!='0')&(title_testing!='1')&(title_testing!='2')&(title_testing!='3')]=4
title_testing=np.array(title_testing, dtype='int')
title_testing
#'Master', 'Miss', 'Mr', 'Mrs'

array([0, 4, 2, 3, 2, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 0, 2, 1, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 3, 1, 2, 2, 2, 1, 2, 4, 2,
       1, 0, 2, 1, 2, 2, 2, 1, 3, 1, 2, 2, 0, 2, 2, 2, 2, 4, 3, 1, 3, 2,
       2, 4, 1, 4, 2, 2, 2, 2, 2, 3, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 0, 1, 1, 2, 1, 0, 1, 1, 4, 4, 2, 2,
       2, 3, 3, 2, 3, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 3, 1, 2, 1, 2,
       1, 2, 2, 1, 2, 0, 2, 1, 3, 1, 1, 2, 2, 2, 3, 1, 3, 1, 1, 2, 1, 2,
       2, 2, 2, 1, 2, 2, 0, 1, 3, 2, 3, 2, 1, 2, 2, 2, 3, 2, 2, 1, 1, 1,
       3, 4, 2, 4, 2, 2, 2, 2, 2, 2, 3, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 4,
       3, 2, 2])

In [8]:
training.describe(include='all')

Pclass                        Name   Sex         Age       SibSp  \
count   668.000000                         668   668  536.000000  668.000000   
unique         NaN                         668     2         NaN         NaN   
top            NaN  Panula, Master. Juha Niilo  male         NaN         NaN   
freq           NaN                           1   427         NaN         NaN   
mean      2.296407                         NaN   NaN   29.700560    0.528443   
std       0.831638                         NaN   NaN   14.240257    1.080327   
min       1.000000                         NaN   NaN    0.670000    0.000000   
25%       2.000000                         NaN   NaN   21.000000    0.000000   
50%       3.000000                         NaN   NaN   29.000000    0.000000   
75%       3.000000                         NaN   NaN   38.250000    1.000000   
max       3.000000                         NaN   NaN   80.000000    8.000000   

             Parch  Ticket        Fare Cabin Embarked    Survived  
count   668.000000     668  668.000000   154      667  668.000000  
unique         NaN     524         NaN   119        3         NaN  
top            NaN  347082         NaN    G6        S         NaN  
freq           NaN       6         NaN     4      484         NaN  
mean      0.407186     NaN   32.064552   NaN      NaN    0.402695  
std       0.854695     NaN   45.320835   NaN      NaN    0.490808  
min       0.000000     NaN    0.000000   NaN      NaN    0.000000  
25%       0.000000     NaN    7.925000   NaN      NaN    0.000000  
50%       0.000000     NaN   14.750000   NaN      NaN    0.000000  
75%       0.000000     NaN   31.275000   NaN      NaN    1.000000  
max       6.000000     NaN  512.329200   NaN      NaN    1.000000

In [9]:
testing.describe(include='all')

Pclass                         Name   Sex         Age       SibSp  \
count   223.000000                          223   223  178.000000  223.000000   
unique         NaN                          223     2         NaN         NaN   
top            NaN  Lindqvist, Mr. Eino William  male         NaN         NaN   
freq           NaN                            1   150         NaN         NaN   
mean      2.345291                          NaN   NaN   29.694775    0.506726   
std       0.850047                          NaN   NaN   15.398053    1.169700   
min       1.000000                          NaN   NaN    0.420000    0.000000   
25%       2.000000                          NaN   NaN   19.250000    0.000000   
50%       3.000000                          NaN   NaN   27.000000    0.000000   
75%       3.000000                          NaN   NaN   37.750000    1.000000   
max       3.000000                          NaN   NaN   71.000000    8.000000   

             Parch   Ticket        Fare    Cabin Embarked  
count   223.000000      223  223.000000       50      222  
unique         NaN      212         NaN       49        3  
top            NaN  CA 2144         NaN  B58 B60        S  
freq           NaN        3         NaN        2      160  
mean      0.304933      NaN   32.622551      NaN      NaN  
std       0.634108      NaN   61.062047      NaN      NaN  
min       0.000000      NaN    0.000000      NaN      NaN  
25%       0.000000      NaN    7.879200      NaN      NaN  
50%       0.000000      NaN   12.475000      NaN      NaN  
75%       0.000000      NaN   30.035400      NaN      NaN  
max       2.000000      NaN  512.329200      NaN      NaN

In [10]:
tr=training
tr=tr.drop('Name', axis=1)
tr.loc[tr['Sex']=='female', 'Sex']=0
tr.loc[tr['Sex']=='male', 'Sex']=1
tr.loc[tr['Age'].isnull(), 'Age']=tr.loc[tr['Age'].notnull() , 'Age'].median()
tr.loc[tr['Embarked'].isnull(), 'Embarked']='S'
tr.loc[tr['Embarked']=='S', 'Embarked']=1
tr.loc[tr['Embarked']=='C', 'Embarked']=2
tr.loc[tr['Embarked']=='Q', 'Embarked']=3
tr.loc[tr['Cabin'].isnull(), 'Cabin']=0
tr.loc[tr['Cabin']!=0, 'Cabin']=1
tr=tr.drop('Ticket', axis=1)
training_data=tr.values
x=training_data[:, :-1]
y=training_data[:, -1]
x=np.append(x, title_training.reshape(-1, 1), axis=1)
x.shape

(668, 9)

In [11]:
ts=testing
ts=ts.drop('Name', axis=1)
ts.loc[ts['Sex']=='female', 'Sex']=0
ts.loc[ts['Sex']=='male', 'Sex']=1
ts.loc[ts['Age'].isnull(), 'Age']=ts.loc[ts['Age'].notnull() , 'Age'].median()
ts.loc[ts['Embarked'].isnull(), 'Embarked']='S'
ts.loc[ts['Embarked']=='S', 'Embarked']=1
ts.loc[ts['Embarked']=='C', 'Embarked']=2
ts.loc[ts['Embarked']=='Q', 'Embarked']=3
ts.loc[ts['Cabin'].isnull(), 'Cabin']=0
ts.loc[ts['Cabin']!=0, 'Cabin']=1
ts=ts.drop('Ticket', axis=1)
testing_data=ts.values
testing_data=np.append(testing_data, title_testing.reshape(-1, 1), axis=1)
testing_data.shape

(223, 9)

In [12]:
testing_data

array([[ 2. ,  1. ,  8. , ...,  0. ,  1. ,  0. ],
       [ 1. ,  0. , 49. , ...,  1. ,  1. ,  4. ],
       [ 3. ,  1. , 27. , ...,  0. ,  3. ,  2. ],
       ...,
       [ 1. ,  0. , 17. , ...,  1. ,  2. ,  3. ],
       [ 3. ,  1. , 43. , ...,  0. ,  1. ,  2. ],
       [ 2. ,  1. , 36.5, ...,  1. ,  1. ,  2. ]])

In [13]:
training_data

array([[ 2.,  0., 29., ...,  0.,  1.,  1.],
       [ 3.,  1., 29., ...,  0.,  1.,  0.],
       [ 2.,  1., 39., ...,  0.,  1.,  0.],
       ...,
       [ 3.,  1., 32., ...,  0.,  1.,  1.],
       [ 3.,  0., 22., ...,  0.,  1.,  0.],
       [ 3.,  0., 29., ...,  0.,  3.,  1.]])

In [14]:
clf=LogisticRegression(solver='saga', max_iter=100000, tol=0.00001)
clf.fit(x, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100000, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='saga',
          tol=1e-05, verbose=0, warm_start=False)

In [ ]:
clf2=RandomForestClassifier(n_estimators=)

In [61]:
predicted=clf.predict(testing_data)

In [62]:
np.savetxt(X=predicted, delimiter=',', fname='titanic predicted.csv', fmt='%.0f')